name: nvidia-h100-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    branches: [ '*' ]
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test-h100-pytorch-2-7:
    name: Test H100 (PyTorch 2.7)
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    uses: ./.github/workflows/reusable-ci-tests.yml
    with:
      runner: 'nvidia-h100-1'
      gpu_type: 'nvidia'
      conda_env_name: 'pytorch_2_7'
      pytorch_version: '2.7.0'
      skip_gpu_check: true

  test-h100-pytorch-nightly:
    name: Test H100 (PyTorch Nightly)
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    uses: ./.github/workflows/reusable-ci-tests.yml
    with:
      runner: 'nvidia-h100-2'
      gpu_type: 'nvidia'
      conda_env_name: 'pytorch_nightly'
      pytorch_version: 'nightly'
      skip_gpu_check: true

  test-h100-pytorch-2-6:
    name: Test H100 (PyTorch 2.6)
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    uses: ./.github/workflows/reusable-ci-tests.yml
    with:
      runner: 'nvidia-h100-3'
      gpu_type: 'nvidia'
      conda_env_name: 'pytorch_2_6'
      pytorch_version: '2.6.0'
      pytorch_cuda_version: 'cu126'
      nvcc_toolkit_version: '12.6.3'
      skip_gpu_check: true
